<script lang="ts">
  import InfoCard from '../components/InfoCard.svelte'; import StatusBadge from '../components/StatusBadge.svelte';
  import { componentStateLabel, formatBytes } from '../lib/status'; import type { AppStatus, CacheStatus, SystemSnapshot } from '../types';
  export let status: AppStatus; export let system: SystemSnapshot; export let cache: CacheStatus;
</script>
<section class="page-stack"><header class="page-header"><div><p class="eyebrow">Plataforma local</p><h1>Panel</h1><p>Estado real del escritorio, motor, modelos y extensión.</p></div><StatusBadge label="Aplicación activa" tone="ok" /></header>
<div class="hero-card"><div><span class="hero-kicker">MilyVoiceTraductor {status.version}</span><h2>Traducción de reuniones sin enviar el audio a una nube.</h2><p>El escritorio administra el runtime; la extensión captura la pestaña elegida y el motor procesa ASR + traducción en localhost.</p></div><div class="hero-mark">EN / 中文<br>→ ES</div></div>
<div class="card-grid"><InfoCard title="Motor IA" value={componentStateLabel(status.engine)} detail="Sidecar local" icon="AI"/><InfoCard title="Modelos" value={`${status.installedModels} instalados`} detail={status.activeModelPack ?? componentStateLabel(status.models)} icon="M"/><InfoCard title="Extensión" value={status.extensionConnected?'Conectada':'Desconectada'} detail="Chromium · localhost" icon="↗"/><InfoCard title="Caché" value={formatBytes(cache.bytes)} detail={`${cache.entries} entradas · límite ${formatBytes(cache.maxBytes)}`} icon="C"/></div>
<div class="two-columns"><article class="panel-card"><div class="panel-title"><h3>Equipo</h3><StatusBadge label="CPU-first" tone="ok"/></div><dl class="details-list"><div><dt>Sistema</dt><dd>{system.operatingSystem}</dd></div><div><dt>Arquitectura</dt><dd>{system.architecture}</dd></div><div><dt>Procesador</dt><dd>{system.cpuBrand}</dd></div><div><dt>CPU lógicas</dt><dd>{system.logicalCpus||'N/D'}</dd></div><div><dt>RAM</dt><dd>{system.totalMemoryMb?`${system.totalMemoryMb} MB`:'N/D'}</dd></div><div><dt>GPU</dt><dd>{system.gpu??'Opcional / no detectada'}</dd></div></dl></article><article class="panel-card"><div class="panel-title"><h3>Privacidad</h3><StatusBadge label="Local" tone="ok"/></div><ul class="check-list"><li><span>✓</span>Audio de reunión procesado en 127.0.0.1.</li><li><span>✓</span>Sin telemetría.</li><li><span>✓</span>Logs sin transcripciones ni token.</li><li><span>✓</span>Guardado de texto opt-in.</li><li><span>✓</span>GPU nunca es requisito para abrir la app.</li></ul></article></div></section>
