[workspace]
resolver = "2"
members = [
  "crates/mily-core",
  "crates/mily-config",
  "crates/mily-database",
  "crates/mily-logging",
  "crates/mily-cache",
  "crates/mily-system",
  "crates/mily-engine",
  "crates/mily-models",
  "crates/mily-sessions",
  "apps/desktop/src-tauri",
]

[workspace.package]
version = "1.0.0-rc.1"
edition = "2024"
license = "MIT"
repository = "https://github.com/LORDMANUEL/milyvoicetraductor"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
